### ISSUE TITLE
Bundle Standards Checklist

### ISSUE THREAD

**Issue by dantleech** [symfony-cmf/blog-bundle#31]
- [ ] [General Bundle Standards](http://symfony.com/doc/master/cmf/contributing/bundles.html#general-bundle-standards)
- [ ] > [File Naming](http://symfony.com/doc/master/cmf/contributing/bundles.html#file-naming)
- [ ] > [Interface Naming](http://symfony.com/doc/master/cmf/contributing/bundles.html#interface-naming)
- [ ] [Meta: README, CHANGELOG, etc](http://symfony.com/doc/master/cmf/contributing/bundles.html#meta-readme-changelog-etc)
- [ ] [Persistence](http://symfony.com/doc/master/cmf/contributing/bundles.html#persistence) #29
- [ ] [Configuration, Files and Formats](http://symfony.com/doc/master/cmf/contributing/bundles.html#configuration-files-and-formats)
- [ ] [Testing Component Integration](http://symfony.com/doc/master/cmf/contributing/bundles.html#testing-component-integration)
